# Basic information
# ----------------------------
title: Protesilaos Stavrou
email: public@protesilaos.com
author: Protesilaos Stavrou
description: "Political analyst. Philosopher. Free software contributor."
baseurl: ""
url: "https://protesilaos.com"
date_format: "%Y-%m-%d"
logo: "/images/brand/protesilaos-logo.png"

# Collections
# ----------------------------

# define collections
collections:
  archive:
    output: true
  archive-codelog:
    output: true
  books:
    output: true
  codelog:
    output: true
  greek:
    output: true
  pages:
    output: true
  schemes:
    output: true
  tempus-themes:
    output: true

# collection defaults
# `group` is used by the `nextprev.html` module (_includes)
# `image` defines a fallback for social media img metadata
# `index` sets the base URL slug
# `master` refers to the catch-all XML feed
defaults:
  - scope:
      type: archive
    values:
      layout: post
      index: "/blog-archive/"
      group: Blog archive entries
      image: "/images/brand/protesilaos-logo.png"
  - scope:
      type: archive-codelog
    values:
      layout: post
      index: "/codelog-archive/"
      group: Code blog archive entries
      image: "/images/brand/protesilaos-logo.png"
  - scope:
      type: books
    values:
      image: "/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: codelog
    values:
      layout: post
      index: "/codelog/"
      group: Code blog entries
      image: "/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: greek
    values:
      layout: elpost
      index: "/greek/"
      group: Αναρτήσεις στα ελληνικά
      image: "/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: pages
    values:
      layout: page
      image: "/images/brand/protesilaos-logo.png"
      master: false
  - scope:
      type: posts
    values:
      layout: post
      index: "/blog/"
      group: Blog entries
      image: "/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: schemes
    values:
      layout: scheme
      index: "/schemes/"
      group: Prot16 schemes
      image: "/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: tempus-themes
    values:
      layout: scheme
      index: "/tempus-themes/"
      group: Tempus Themes
      image: "/images/brand/protesilaos-logo.png"
      master: true

# Plugin settings
# ----------------------------

# social SEO
social:
  name: Protesilaos Stavrou
  links:
    - https://github.com/protesilaos
    - https://gitlab.com/protesilaos
    - https://www.reddit.com/user/protesilaos

# Where things are
# ----------------------------
source:       .
destination:  _site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Build settings
# ----------------------------
incremental: false
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  footnote_backlink: ^
  hard_wrap: false
  syntax_highlighting: rouge
  syntax_highlighter_opts:
    disable : true # disable syntax highlighting
highlighter: none # disable syntax highlighting
permalink: pretty
sass:
  style: compressed
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - Gemfile
  - vendor
  - package.json
  - node_modules
  - gulpfile.js
  - .stylelintrc
