environment: development # to exclude assets from local setup
limit_posts: 1
incremental: false
exclude:
  - README.md # ------------------ Basis ---------------------------
  - .bundle
  - .git
  - .gitignore
  - .stylelintrc
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor
  - _archive/ # ------------------ Unusual -------------------------
  - _pages/indices/blog-archive.html
  - _assets/css
  - _assets/js
  - _archive-codelog
  - _pages/indices/codelog-archive.html
  - 404.md
  - _includes/cypher-guest.scss
  - _includes/guestbox.html
  - css/cypher-print.css
  - master.xml
  - static
  - js # ------------------------- JavaScript ----------------------
  - fonts # ---------------------- Webfonts ------------------------
  - css/webfonts.min.css
  - images # --------------------- Images --------------------------
  - android-chrome-192x192.png
  - android-chrome-256x256.png
  - apple-touch-icon.png
  - browserconfig.xml
  - favicon-16x16.png
  - favicon-32x32.png
  - favicon.ico
  - manifest.json
  - mstile-150x150.png
  - safari-pinned-tab.svg
  - site.webmanifest
  - _posts # --------------------- Posts ---------------------------
  - _layouts/post.html
  - _posts/2016
  - _posts/2017
  - _posts/opeds
  - _posts/seminars
  - _layouts/seminar.html
  - _pages/indices/seminars.html
  - _pages # --------------------- Pages ---------------------------
  - _pages/blog
  - _pages/indices
  - _layouts/index.html
  - _layouts/page.html
  - _data/text.yml
  - _data/gitprojects.yml
  - greek.xml # ------------------ Greek ---------------------------
  - _greek
  - _pages/indices/greek.html
  - _layouts/elpost.html
  - news.xml # ------------------- News & Announcements ------------
  - _news
  - _pages/indices/news.html
  - _books # --------------------- Books ---------------------------
  - _data/books.yml
  - _books/eudi
  - _books/euguide
  - _books/euhandbook
  - _books/hsw
  - _books/sov
  - _books/stsns
  - _pages/books
  - _pages/indices/books.html
  - _layouts/eudi.html
  - _layouts/euguide.html
  - _layouts/euhandbook.html
  - _layouts/hsw.html
  - _layouts/print.html
  - _layouts/sov.html
  - _layouts/stsns.html
  - _layouts/monograph.html
  - _includes/booksnav.html
  - _includes/cypher-books.scss
  - _codelog # ------------------- Code ----------------------------
  - _codelog/2017
  - codelog.xml
  - _pages/indices/codelog.html
  - _pages/indices/code.html
  - _includes/cypher-code.scss
  - _schemes # ------------------- Schemes -------------------------
  - _data/themes.yml
  - _includes/prot16-packages.html
  - _includes/prot16-palette.html
  - _includes/prot16-project-template.md
  - _includes/prot16-project-template.md
  - _includes/prot16-vim-packages.html
  - _layouts/scheme.html
  - _pages/indices/schemes.html
  - _tempus-themes
  - _data/tempus-themes-packages.yml
  - _data/tempus-themes-repos.yml
  - _data/tempus-themes.yml
  - _includes/tempus-themes-packages.html
  - _includes/tempus-themes-palette.html
  - _includes/tempus-themes-project-template.md
  - _includes/tempus-themes-repos.html
  - _pages/indices/tempus-themes.html
